### ISSUE TITLE
'fxcored query slashing signing-info' no longer works as expected

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-docs#15]
As suggested at <https://github.com/FunctionX/fx-core/issues/55>, we should use:

    fxcored query slashing signing-info $(fxcored tendermint show-validator)

instead of:

    fxcored query slashing signing-info $(fxcored tendermint show-address)

Affected docs pages:

- <https://functionx.gitbook.io/home/f-x-core-tutorials/f-x-cored-commands-documentation#signing-info>
- <https://functionx.gitbook.io/home/validators/validator-setup#track-validator-signing-information>

**Comment by zakir-web3** [comment]
The documentation has been updated, thanks
